#!/bin/bash

THEMESDIR=$(dirname "$0")

clear_all_themes() {
  # Delete all the existing theme "roms"
  for themefile in $THEMESDIR/*.sh; do
    if [ -f "$themefile" ]; then
      rm "$themefile"
    fi
  done
}

generate_themes() {
  # Loop through all directories in SRC
  for dir in $THEMESDIR/*; do
    
    # Check if the current directory is a directory (not a file)
    if [ -d "$dir" ]; then
      
      # Get the directory name
      themename="$(busybox basename "$dir")"
      
      # Create a new file in DEST with the same name as the directory
      themesh="$THEMESDIR/$themename.sh"

      # pipe commands into new script file
      echo "#!/bin/sh" > "$themesh"

      for folder in skin font lang rgui
      do
          if [ -d "$dir/$folder" ]; then
              echo "cp -rv \"$THEMESDIR/$themename/$folder\" \"/mnt/mmc/CFW\"" >> "$themesh"
          fi
      done

      if [ -f "$dir/boot_logo.bmp.gz" ]; then
          echo "cp -v \"$THEMESDIR/$themename/boot_logo.bmp.gz\" \"/mnt/mmc/CFW\"" >> "$themesh"
          # todo - remount something?
      fi
    fi
  done
}

rumble_success() {
  echo 50 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 60 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 70 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
}

rumble_fail() {
  echo 60 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.4
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 40 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.4
  echo 0 > "/sys/class/power_supply/battery/moto"
}

clear_all_themes
generate_themes
rumble_success