#!/bin/sh

rootDir=$(busybox dirname $(busybox dirname $(busybox dirname "$0")))
pdfDir="$rootDir/PDFs"
romsDir="$rootDir/Roms"
readDir=$(busybox dirname "$0")

# Delete all the existing scripts so we start fresh
rm "$readDir"/*.sh

# find all PDF files in /PDFs and iterate over them
busybox find $pdfDir -name "*.pdf" | while read pdf_file
do
    # in a sub function, need new variables
    rootDir=$(busybox dirname $(busybox dirname "$pdf_file"))

    # extract the filename without extension
    filename=$(busybox basename "$pdf_file" .pdf)

    # create the new shell script file
    sh_file="$rootDir/Roms/Read/$filename.sh"

    echo "#!/bin/sh
    # launch it
    $rootDir/Roms/Read/.utils/fbpdf \"$pdf_file\"
    wait
    exit" > "$sh_file"

done

# find all PDF files in /Roms/*/Manuals/ and iterate over them
busybox find "$romsDir" -path "*/Manuals/*.pdf" | while read pdf_file
do
    # in a sub function, need new variables
    # ugly but it works :shrug:
    rootDir=$(busybox dirname $(busybox dirname $(busybox dirname $(busybox dirname "$pdf_file"))))

    # extract the filename without extension
    filename=$(busybox basename "$pdf_file" .pdf)

    # create the new shell script file
    sh_file="$rootDir/Roms/Read/$filename.sh"

    echo "#!/bin/sh
    # launch it
    $rootDir/Roms/Read/.utils/fbpdf \"$pdf_file\"
    wait
    exit" > "$sh_file"

done

rumble_success() {
  echo 50 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 60 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 70 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
}

rumble_success