#!/bin/bash

THEMESDIR=$(busybox dirname "$0")

clear_all_themes() {
  # Delete all the existing theme "roms"
  for themefile in $THEMESDIR/*.sh; do
    if [ -f "$themefile" ]; then
      rm "$themefile"
    fi
  done
}

noFolders=0
generate_themes() {
  for dir in "$THEMESDIR"/*/; do

    if [ "$dir" == "$THEMESDIR/*/" ]; then
      # no folders found
      noFolders=1
      continue
    fi

    if [ "$dir" == */.* ]; then
      # exclude "hidden" . folders
      continue
    fi

    # Get the directory name
    themename=$(busybox basename "$dir")
    
    # Create a new file in DEST with the same name as the directory
    themesh="$THEMESDIR/$themename.sh"
    bootlogosh="$THEMESDIR/$themename - boot logo.sh"
    iconssh="$THEMESDIR/$themename - icons only.sh"

    # pipe commands into new script file
    echo "#!/bin/sh

for folder in skin font lang
do
    if [ -d \"/mnt/mmc/CFW/\$folder\" ]; then

        # delete everything in this theme related folder
        rm -r \"/mnt/mmc/CFW/\$folder/*\"

        # copy in the default files from garlic os
        cp -r \"$THEMESDIR/.garlicos/\$folder\" \"/mnt/mmc/CFW\"
    fi
done
    " > "$themesh"

    for folder in skin font lang rgui; do
        if [ -d "$dir/$folder" ]; then
            echo "cp -rv \"$THEMESDIR/$themename/$folder\" \"/mnt/mmc/CFW\"" >> "$themesh"
        fi
    done

    if [ -d "$dir/skin/system" ]; then
      echo "#!/bin/sh
cp -rv \"$THEMESDIR/$themename/skin/system\" \"/mnt/mmc/CFW/skin\"

echo 50 > \"/sys/class/power_supply/battery/moto\"
busybox sleep 0.2
echo 0 > \"/sys/class/power_supply/battery/moto\"
      " > "$iconssh"
    fi

    if [ -f "$dir/misc/boot_logo.bmp.gz" ]; then
      echo "#!/bin/sh
mount -o remount,rw /misc
cp -r \"$THEMESDIR/$themename/misc/boot_logo.bmp.gz\" \"/misc/boot_logo.bmp.gz\"
mount -o remount,ro /misc

echo 50 > \"/sys/class/power_supply/battery/moto\"
busybox sleep 0.2
echo 0 > \"/sys/class/power_supply/battery/moto\"
      " > "$bootlogosh"
    fi

    echo "
echo 50 > \"/sys/class/power_supply/battery/moto\"
busybox sleep 0.2
echo 0 > \"/sys/class/power_supply/battery/moto\"
    " >> "$themesh"
  done
}

add_default_theme() {
  echo "#!/bin/sh

for folder in skin font lang
do
  # delete everything in this theme related folder
  rm -r \"/mnt/mmc/CFW/\$folder/*\"

  # copy in the default files from garlic os
  cp -r \"$THEMESDIR/.garlicos/\$folder\" \"/mnt/mmc/CFW\"
done

echo 50 > \"/sys/class/power_supply/battery/moto\"
busybox sleep 0.2
echo 0 > \"/sys/class/power_supply/battery/moto\"
    " > "$THEMESDIR/Garlic OS Default.sh"

    echo "#!/bin/sh
# copy in the default files from garlic os
mount -o remount,rw /misc
cp -r \"$THEMESDIR/.garlicos/misc/boot_logo.bmp.gz\" \"/misc/boot_logo.bmp.gz\"
mount -o remount,ro /misc

echo 50 > \"/sys/class/power_supply/battery/moto\"
busybox sleep 0.2
echo 0 > \"/sys/class/power_supply/battery/moto\"
    " > "$THEMESDIR/Garlic OS Default - boot logo.sh"
}

rumble_success() {
  echo 50 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 60 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 70 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
}

rumble_fail() {
  echo 60 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.4
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 40 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.4
  echo 0 > "/sys/class/power_supply/battery/moto"
}

clear_all_themes
generate_themes
add_default_theme

if [ $noFolders == 1 ]; then
  rumble_fail
else
  rumble_success
fi
