#!/bin/bash

rootDir=$(busybox dirname $(busybox dirname $(busybox dirname "$0")))
rootThemesDir="$rootDir/Themes"
rootBootLogosDir="$rootDir/BootLogos"
rootSystemIconsDir="$rootDir/SystemIcons"

# All the output scripts go here
skinsDir=$(busybox dirname "$0")

$skinsDir/.utils/printstr "    Refreshing...   " & sleep 1

# Create the image preview folder if it doesn't exit
mkdir -p "$skinsDir/Imgs"
imgsDir="$skinsDir/Imgs"

# Consistent suffixes
themeSuffix=" - theme"
bootLogoSuffix=" - boot logo"
iconSuffix=" - system icons"

rumble="
echo 50 > \"/sys/class/power_supply/battery/moto\"
busybox sleep 0.2
echo 0 > \"/sys/class/power_supply/battery/moto\"
"

clear_all_themes() {
  # Delete all the existing theme "roms"
  for file in $skinsDir/*.sh; do
    if [ -f "$file" ]; then
      rm "$file"
    fi
  done

  # Clear any old previews
  rm "$imgsDir/*"
}

noThemeFolders=0
generate_themes() {
  for dir in "$rootThemesDir"/*/; do

    if [ "$dir" == "$rootThemesDir/*/" ]; then
      # no folders found
      noThemeFolders=1
      continue
    fi

    if [ "$dir" == */.* ]; then
      # exclude "hidden" . folders
      continue
    fi

    # Get the directory name
    themeName=$(busybox basename "$dir")
    
    # Setup the output script names
    themeSh="$skinsDir/$themeName$themeSuffix.sh"
    bootLogoSh="$skinsDir/$themeName$bootLogoSuffix.sh"
    #iconsSh="$skinsDir/$themeName$iconSuffix.sh"

    # If this folder has theme elements
    if [ -d "$dir/skin" ] || [ -d "$dir/font" ] || [ -d "$dir/lang" ]; then

      # Delete skin, font and lang folders, replace with garlic os defaults
      echo "#!/bin/sh

      $skinsDir/.utils/printstr \"    Switching theme...   \" & sleep 1

      for folder in skin font lang
      do
        if [ -d \"/mnt/mmc/CFW/\$folder\" ]; then

          # delete everything in this theme related folder
          rm -r \"/mnt/mmc/CFW/\$folder/*\"

          # copy in the default files from garlic os
          cp -r \"$skinsDir/.garlicos/\$folder\" \"/mnt/mmc/CFW\"
        fi
      done
      " > "$themeSh"

      # For each part of the theme, add a copy action
      # Note the inclusion of rgui folder
      for folder in skin font lang rgui; do
        if [ -d "$dir/$folder" ]; then
          echo "cp -rv \"$rootThemesDir/$themeName/$folder\" \"/mnt/mmc/CFW\"" >> "$themeSh"
        fi
      done

      echo "$rumble" >> "$themeSh"

      # COMMENTED OUT THE BELOW BECAUSE MOST THEMES JUST USE GARLIC OS SYSTEM ICONS
      # # If the theme has an icon set, pull it out to it's own script
      # if [ -d "$dir/skin/system" ]; then
      #   echo "#!/bin/sh
      #   cp -rv \"$rootThemesDir/$themeName/skin/system\" \"/mnt/mmc/CFW/skin\"
      #   $rumble" > "$iconsSh"
      # fi

      # copy the preview if it exists
      if [ -f "$dir/Imgs/$themeName.png" ]; then
        cp "$dir/Imgs/$themeName.png" "$imgsDir/$themeName$themeSuffix.png"
      elif [ -d "$dir/imgs" ]; then
        cp "$dir/imgs/$themeName.png" "$imgsDir/$themeName$themeSuffix.png"
      fi
    fi

    # If the folder has a boot logo, pull it out to it's own script
    if [ -f "$dir/misc/boot_logo.bmp.gz" ]; then
      echo "#!/bin/sh

      $skinsDir/.utils/printstr \"    Switching boot logo...   \" & sleep 1

      mount -o remount,rw /misc
      cp -r \"$rootThemesDir/$themeName/misc/boot_logo.bmp.gz\" \"/misc/boot_logo.bmp.gz\"
      mount -o remount,ro /misc
      $rumble" > "$bootLogoSh"

      # copy the preview
      busybox gzip -dc "$dir/misc/boot_logo.bmp.gz" > "$imgsDir/$themeName$bootLogoSuffix.png"
    fi

  done
}

noBootLogoFolders=0
generate_bootlogos() {
  for dir in "$rootBootLogosDir"/*/; do

    if [ "$dir" == "$rootBootLogosDir/*/" ]; then
      # no folders found
      noBootLogoFolders=1
      continue
    fi

    if [ "$dir" == */.* ]; then
      # exclude "hidden" . folders
      continue
    fi

    # Get the directory name
    themeName=$(busybox basename "$dir")
    
    # Setup the output script names
    bootLogoSh="$skinsDir/$themeName$bootLogoSuffix.sh"

    # If the folder has a boot logo, pull it out to it's own script
    if [ -f "$dir/misc/boot_logo.bmp.gz" ]; then
      echo "#!/bin/sh

      $skinsDir/.utils/printstr \"    Switching boot logo...   \" & sleep 1

      mount -o remount,rw /misc
      cp -r \"$rootThemesDir/$themeName/misc/boot_logo.bmp.gz\" \"/misc/boot_logo.bmp.gz\"
      mount -o remount,ro /misc
      $rumble" > "$bootLogoSh"

      # copy the preview
      busybox gzip -dc "$dir/misc/boot_logo.bmp.gz" > "$imgsDir/$themeName$bootLogoSuffix.png"
    fi

  done
}

noSystemIconFolders=0
generate_systemicons() {
  for dir in "$rootSystemIconsDir"/*/; do

    if [ "$dir" == "$rootSystemIconsDir/*/" ]; then
      # no folders found
      noSystemIconFolders=1
      continue
    fi

    if [ "$dir" == */.* ]; then
      # exclude "hidden" . folders
      continue
    fi

    # Get the directory name
    themeName=$(busybox basename "$dir")
    
    # Setup the output script names
    iconsSh="$skinsDir/$themeName$iconSuffix.sh"

    # If this folder is actually an icon set, make it into it's own script
    if [ -d "$dir/system" ]; then
      echo "#!/bin/sh

      $skinsDir/.utils/printstr \"    Switching system icons...   \" & sleep 1

      cp -rv \"$rootSystemIconsDir/$themeName/system\" \"/mnt/mmc/CFW/skin\" $rumble" > "$iconsSh"

      # copy the preview if it exists
      if [ -f "$dir/Imgs/$themeName.png" ]; then
        cp "$dir/Imgs/$themeName.png" "$imgsDir/$themeName$iconSuffix.png"
      elif [ -d "$dir/imgs" ]; then
        cp "$dir/imgs/$themeName.png" "$imgsDir/$themeName$iconSuffix.png"
      fi
    fi

  done
}

add_defaults() {
  echo "#!/bin/sh

$skinsDir/.utils/printstr \"    Resetting theme & icons...   \" & sleep 1

for folder in skin font lang
do
  # delete everything in this theme related folder
  rm -r \"/mnt/mmc/CFW/\$folder/*\"

  # copy in the default files from garlic os
  cp -r \"$skinsDir/.garlicos/\$folder\" \"/mnt/mmc/CFW\"
done

$rumble" > "$skinsDir/Garlic OS$themeSuffix.sh"

    echo "#!/bin/sh
# copy in the default files from garlic os

$skinsDir/.utils/printstr \"    Resetting boot logo...   \" & sleep 1

mount -o remount,rw /misc
cp -r \"$skinsDir/.garlicos/misc/boot_logo.bmp.gz\" \"/misc/boot_logo.bmp.gz\"
mount -o remount,ro /misc

$rumble" > "$skinsDir/Garlic OS$bootLogoSuffix.sh"
}

rumble_success() {
  echo 50 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 60 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 70 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.2
  echo 0 > "/sys/class/power_supply/battery/moto"
}

rumble_fail() {
  echo 60 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.4
  echo 0 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.1
  echo 40 > "/sys/class/power_supply/battery/moto"
  busybox sleep 0.4
  echo 0 > "/sys/class/power_supply/battery/moto"
}

clear_all_themes
generate_themes
generate_bootlogos
generate_systemicons
add_defaults

if [ $noThemesFolders == 1 ] && [ $noBootLogoFolders == 1 ] && [ $noSystemIconFolders == 1 ]; then
  rumble_fail
else
  rumble_success
fi
